"""Import and sandboxed reader routes for local ZIM archives."""

from __future__ import annotations

import logging
import os
import re

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import HTMLResponse, Response
from pydantic import BaseModel, Field

from api import zim_library, zim_reader
from api.security import sanitize_error_message

logger = logging.getLogger(__name__)
router = APIRouter(tags=["zim"])


class ZimImportRequest(BaseModel):
    path: str = Field(..., description="Absolute filesystem path to a .zim file")


def _register_zim_path(path: str) -> zim_library.ZimEntry:
    archive = zim_reader.open_archive(path)
    metadata = zim_reader.get_metadata(archive)
    return zim_library.register(
        path=path,
        title=metadata["title"],
        description=metadata["description"],
        article_count=metadata["articleCount"],
    )


@router.post("/api/zim/import")
async def import_zim(request: ZimImportRequest):
    path = request.path.strip()
    if not path:
        raise HTTPException(status_code=400, detail="No path provided")
    if not os.path.isfile(path):
        raise HTTPException(status_code=400, detail=f"File not found: {path}")
    try:
        return _register_zim_path(path)
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Failed to open ZIM file %s: %s", path, exc)
        raise HTTPException(status_code=400, detail="Not a valid .zim file") from exc


@router.get("/api/zim/drop_dir")
async def get_zim_drop_dir():
    return {"path": zim_library.ZIM_DROP_DIR}


@router.post("/api/zim/rescan")
async def rescan_zim_drop_dir():
    already_registered = zim_library.registered_paths()
    added: list[zim_library.ZimEntry] = []
    errors: list[dict] = []
    for path in zim_library.list_drop_dir_zim_files():
        if path in already_registered:
            continue
        try:
            added.append(_register_zim_path(path))
        except Exception as exc:
            logger.error("Failed to auto-register dropped ZIM file %s: %s", path, exc)
            errors.append({"path": path, "error": sanitize_error_message(exc)})
    return {"added": added, "errors": errors}


def _get_zim_entry_or_404(zim_id: str) -> zim_library.ZimEntry:
    entry = zim_library.get(zim_id)
    if entry is None:
        raise HTTPException(status_code=404, detail="ZIM archive not found in library")
    return entry


_ZIM_HTML_HEADERS = {
    "X-Content-Type-Options": "nosniff",
    "Content-Security-Policy": "default-src 'self' data:; img-src 'self' data: blob:; "
    "style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; "
    "connect-src 'none'; base-uri 'self'; frame-ancestors 'self'",
}


def _open_zim_or_500(entry: zim_library.ZimEntry):
    try:
        return zim_reader.open_archive(entry["path"])
    except Exception as exc:
        logger.error("Failed to open registered ZIM file %s: %s", entry["path"], exc)
        raise HTTPException(status_code=500, detail="Could not open ZIM file") from exc


@router.get("/api/zim/{zim_id}")
async def get_zim_metadata(zim_id: str):
    entry = _get_zim_entry_or_404(zim_id)
    archive = _open_zim_or_500(entry)
    return {**entry, **zim_reader.get_metadata(archive)}


@router.get("/api/zim/{zim_id}/search")
async def search_zim(
    zim_id: str,
    q: str = Query(..., min_length=1),
    limit: int = Query(20, ge=1, le=100),
):
    entry = _get_zim_entry_or_404(zim_id)
    return zim_reader.search_entries(_open_zim_or_500(entry), q, limit=limit)


@router.get("/api/zim/{zim_id}/index")
async def get_zim_index(zim_id: str, limit: int = Query(500, ge=1, le=2000)):
    entry = _get_zim_entry_or_404(zim_id)
    return zim_reader.build_title_index(_open_zim_or_500(entry), limit=limit)


def _zim_visible_text(html: str) -> str:
    text = re.sub(r"(?is)<script[^>]*>.*?</script>", " ", html)
    text = re.sub(r"(?is)<style[^>]*>.*?</style>", " ", text)
    text = re.sub(r"(?is)<[^>]+>", " ", text)
    text = text.replace("&nbsp;", " ").replace("&amp;", "&")
    text = text.replace("&lt;", "<").replace("&gt;", ">").replace("&quot;", '"')
    return " ".join(text.split()).strip()


_ZIM_LOADING_PLACEHOLDER_RE = re.compile(
    r"(?i)(\bloading\b|cargando|carga|chargement|changement|"
    r"加载|载入|読み込み|ロード中|불러오는|로딩|carregando|laden|laddar|"
    r"betölt|yüklen|иниц|загруз|oczekiwan|spuštan|nalagan|betölt|"
    r"\.\s*\.\s*\.\s*$)"
)
_ZIM_JS_SHELL_NOTICE = (
    '<div style="position:fixed;inset:0;display:flex;align-items:center;'
    'justify-content:center;text-align:center;font:14px/1.5 system-ui,sans-serif;'
    'color:#333;background:#fff;padding:24px;box-sizing:border-box;z-index:2147483647;">'
    '<div style="max-width:34em;"><b>This page is a JavaScript app.</b><br><br>'
    "Its content is generated by scripts inside the archive, which are disabled "
    "in the reader sandbox for safety. The archive did not ship a static "
    "fallback for this entry. Try another article from the list on the left."
    "</div></div>"
)


def _is_zim_js_shell(html: str) -> bool:
    text = _zim_visible_text(html)
    return bool(text and len(text) <= 60 and _ZIM_LOADING_PLACEHOLDER_RE.search(text))


def _maybe_inject_zim_js_shell_notice(html: str) -> str:
    if not _is_zim_js_shell(html):
        return html
    if re.search(r"(?i)<body[^>]*>", html):
        return re.sub(
            r"(?i)(<body[^>]*>)", r"\1" + _ZIM_JS_SHELL_NOTICE, html, count=1
        )
    return _ZIM_JS_SHELL_NOTICE + html


def _rewrite_zim_html(zim_id: str, entry_path: str, html_bytes: bytes) -> str:
    html = html_bytes.decode("utf-8", errors="replace")
    entry_dir = entry_path.rsplit("/", 1)[0] + "/" if "/" in entry_path else ""
    base_tag = f'<base href="/api/zim/{zim_id}/raw/{entry_dir}">'
    if re.search(r"(?i)<head[^>]*>", html):
        html = re.sub(r"(?i)(<head[^>]*>)", r"\1" + base_tag, html, count=1)
    else:
        html = base_tag + html
    return _maybe_inject_zim_js_shell_notice(html)


@router.get("/api/zim/{zim_id}/entry", response_class=HTMLResponse)
async def get_zim_entry(zim_id: str, path: str = Query(...)):
    entry = _get_zim_entry_or_404(zim_id)
    try:
        content, mimetype = zim_reader.get_entry_content(_open_zim_or_500(entry), path)
    except Exception as exc:
        raise HTTPException(status_code=404, detail=f"Entry not found: {path}") from exc
    if not mimetype.startswith("text/html"):
        return Response(content=content, media_type=mimetype)
    return HTMLResponse(
        content=_rewrite_zim_html(zim_id, path, content),
        headers=_ZIM_HTML_HEADERS,
    )


@router.get("/api/zim/{zim_id}/raw/{entry_path:path}")
async def get_zim_raw(zim_id: str, entry_path: str):
    entry = _get_zim_entry_or_404(zim_id)
    try:
        content, mimetype = zim_reader.get_entry_content(
            _open_zim_or_500(entry), entry_path
        )
    except Exception as exc:
        raise HTTPException(status_code=404, detail=f"Entry not found: {entry_path}") from exc
    if mimetype.startswith("text/html"):
        return HTMLResponse(
            content=_rewrite_zim_html(zim_id, entry_path, content),
            headers=_ZIM_HTML_HEADERS,
        )
    return Response(
        content=content,
        media_type=mimetype,
        headers={"X-Content-Type-Options": "nosniff"},
    )


@router.delete("/api/zim/{zim_id}")
async def delete_zim(zim_id: str):
    entry = _get_zim_entry_or_404(zim_id)
    zim_reader.close_archive(entry["path"])
    zim_library.unregister(zim_id)
    return {"message": "ZIM archive removed from library"}
