#!/usr/bin/env python3
"""Generate/check the documented environment registry."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from api.settings import PUBLIC_ENVIRONMENT_VARIABLES  # noqa: E402

DESTINATION = ROOT / "hackdeepwiki.env.example"

VALUES = {
    "HACKDEEPWIKI_DEPLOYMENT_PROFILE": "trusted-lan",
    "HACKDEEPWIKI_HOST": "0.0.0.0",
    "HACKDEEPWIKI_AUTH_MODE": "true",
    "HACKDEEPWIKI_AUTH_CODE": "replace-with-a-long-random-secret",
    "HACKDEEPWIKI_API_PORT": "8001",
    "HACKDEEPWIKI_PROJECT_NAME": "hackdeepwiki-local",
    "HACKDEEPWIKI_NETWORK_MODE": "auto",
}

EXTERNAL = (
    ("OLLAMA_ENDPOINT", "http://127.0.0.1:11434"),
    ("OLLAMA_MODEL", ""),
    ("OLLAMA_EMBED_MODEL", ""),
    ("OLLAMA_EMBED_BATCH_SIZE", "32"),
    ("OLLAMA_REQUEST_TIMEOUT", "1800"),
    ("OLLAMA_HEALTH_TIMEOUT", "60"),
    ("GITHUB_TOKEN", ""),
)


def render() -> str:
    lines = [
        "# Generated by scripts/generate_env_example.py.",
        "# Copy to hackdeepwiki.env and change only the settings you need.",
        "# This example is secure for the Docker/LAN launcher by default.",
        "",
        "# Provider/runtime helpers",
    ]
    lines.extend(f"{name}={value}" for name, value in EXTERNAL)
    lines.extend(["", "# HackDeepWiki settings"])
    for name, description in PUBLIC_ENVIRONMENT_VARIABLES.items():
        lines.append(f"# {description}")
        if name in VALUES:
            lines.append(f"{name}={VALUES[name]}")
        else:
            lines.append(f"# {name}=")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not DESTINATION.is_file() or DESTINATION.read_text(
            encoding="utf-8"
        ) != expected:
            print(
                "hackdeepwiki.env.example is stale; run "
                "python scripts/generate_env_example.py"
            )
            return 1
        return 0
    DESTINATION.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
